### ISSUE TITLE
Add a repo_names option to the ohioit.github.repository_information module.

### ISSUE THREAD

**Issue by klfgit** [ohioit/ansible-collection-github#16]
As an Ansible user, I would like to fetch information about  list of repositories using the repository_information module.
Below is an example of the desired interface.  The module should return information for all listed repositories.  If one of the listed repositories is not found the task should fail.

```yaml

  tasks:
    - name: Get Repo Information
      ohioit.github.repository_information:
        token: a_token
        enterprise_url: https://github.ohio.edu/api/v3
        organization_name: OIT
        repo_names:
            - repo_1
            - repo_2
            - repo_n
      register: result
```
